### ISSUE TITLE
Implement server module

### ISSUE THREAD

**Issue by lemarco** [lecala/server#4]

**Comment by agniev-a-hub** [comment]
Server should listen specific port.

Server should register handlers. 

Protocol: passsed as a strategy. 

Methods: 
start - init server
stop - kill server
consctructor - creates server
error - ...
send - message to the client, in http transport - f.e. - response. In websocket transport - push from the server. 
createContext - ...
log - ...

ADD:
Client class, stored in some server Map() object. 
What should contain:
session should be implemented via Client, not Server.
